info:
  name: 订单服务
  contact: 动脑学院VIP

server:
  port: 9001

spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/order-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '{cipher}54afbcfe3a6d23f52ff36c17104894ab199621c7dc709f55f209ff295e5bcfbd'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
  cloud:
    # stream相关配置
    stream:
      default:
        # 消息内容序列化格式
        contentType: application/json
      # 通道设置
      bindings:
        # 短信通道相关配置
        sms-send:
          # 绑定具体的mq实现
          binder: mq1
          destination: sms-send
          contentType: application/json
        # 订单事件
        order-event:
          binder: mq1
          contentType: application/json
      # 具体接入的mq实现 
      binders:
        # 命名为mq1，使用rabbitmq
        mq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest