server:
  port: 9005
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/sms-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '{cipher}b82949bf7dc9e93d566e01a9af5bedbacf4ff184a024611a5675cc3bd3863e8e'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
  cloud:
    # stream相关配置
    stream:
      default:
        # 消息内容序列化格式
        contentType: application/json
      # 通道设置
      bindings:
        # 短信通道相关配置
        sms-send:
          # 绑定具体的mq实现
          binder: mq1
          destination: sms-send
          group: sms-send
          contentType: application/json
      # 具体接入的mq实现 
      binders:
        # 命名为mq1，使用rabbitmq
        mq1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
