info:
  name: 用户中心-yuan
  contact: 动脑学院VIP

server:
  port: 9004
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/uaa-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '{cipher}b82949bf7dc9e93d566e01a9af5bedbacf4ff184a024611a5675cc3bd3863e8e'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
    
