info:
  name: 仓储服务
  contact: 动脑学院VIP

server:
  port: 9002

spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/wms-db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '{cipher}54afbcfe3a6d23f52ff36c17104894ab199621c7dc709f55f209ff295e5bcfbd'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
